export const intakeOptions = [
    { value: 'January', label: 'January' },
    { value: 'February', label: 'February' },
    { value: 'March', label: 'March' },
    { value: 'April', label: 'April' },
    { value: 'May', label: 'May' },
    { value: 'June', label: 'June' },
    { value: 'July', label: 'July' },
    { value: 'August', label: 'August' },
    { value: 'September', label: 'September' },
    { value: 'October', label: 'October' },
    { value: 'November', label: 'November' },
    { value: 'December', label: 'December' },
];

export const yearOptions = [
    { value: '2021', label: '2021' },
    { value: '2022', label: '2022' },
    { value: '2023', label: '2023' },
    { value: '2024', label: '2024' },
    { value: '2025', label: '2025' },
    { value: '2026', label: '2026' },
];

export const countryOptions = [
    { value: "1", label: "United States of America" },
    { value: "2", label: "Australia" },
    { value: "3", label: "Canada" },
    { value: "4", label: "United Kingdom" },
    { value: "5", label: "New Zealand" },
    { value: "6", label: "Singapore" },
    { value: "7", label: "Dubai" },
    { value: "8", label: "Ireland" },
    { value: "9", label: "Germany" },
    { value: "10", label: "France" },
    { value: "11", label: "Sweden" },
    { value: "12", label: "Netherlands" },
    { value: "13", label: "Austria" },
    { value: "14", label: "Denmark" },
    { value: "15", label: "Finland" },
    { value: "16", label: "Italy" },
    { value: "17", label: "Hungary" },
    { value: "18", label: "Switzerland" },
    { value: "19", label: "Spain" },
    { value: "20", label: "Lithuania" },
    { value: "22", label: "Cyprus" },
    { value: "23", label: "Poland" },
    { value: "25", label: "Malaysia" },
    { value: "26", label: "Mauritius" },
    { value: "32", label: "China" },
    { value: "35", label: "Vietnam" },
    { value: "37", label: "Malta" },
    { value: "38", label: "Japan" },
    { value: "39", label: "Belgium" },
    { value: "40", label: "Russia" },
    { value: "41", label: "South Korea" },
    { value: "45", label: "India" },
    { value: "46", label: "Georgia" },
];
export const yearsOption = [
    { value: "2024", label: "2024" },
    { value: "2025", label: "2025" },
    { value: "2026", label: "2026" },
    { value: "2027", label: "2027" },
  ];

  export const IntakeYearsoptions = [
    { value: "*", label: "All" },
    { value: "1", label: "January" },
    { value: "2", label: "February" },
    { value: "3", label: "March" },
    { value: "4", label: "April" },
    { value: "5", label: "May" },
    { value: "6", label: "June" },
    { value: "7", label: "July" },
    { value: "8", label: "August" },
    { value: "9", label: "September" },
    { value: "10", label: "October" },
    { value: "11", label: "November" },
    { value: "12", label: "December" },
    { value: "13", label: "Spring" },
    { value: "14", label: "Summer" },
    { value: "15", label: "Fall" },
    { value: "16", label: "Winter" },
  ];
 export const ProgramLevelData = [
    { id: 1, label: "High School (11th - 12th)" },
    { id: 2, label: "UG Diploma/ Certificate/ Associate Degree" },
    { id: 3, label: "PG Diploma/Certificate" },
    { id: 4, label: "PG" },
    { id: 5, label: "UG+PG (Accelerated) Degree" },
    { id: 6, label: "Foundation" },
    { id: 7, label: "Short Term Programs" },
    { id: 8, label: "Pathway Programs" },
    { id: 9, label: "Twinning Programmes (UG)" },
    { id: 10, label: "Twinning Programmes (PG)" },
    { id: 11, label: "English Language Program" },
    { id: 12, label: "Online Programmes / Distance Learning" },
  ];  

  export const RequirementsData = [
    { id: 1, label: "PTE" },
    { id: 2, label: "TOEFL iBT" },
    { id: 3, label: "IELTS" },
    { id: 4, label: "DET" },
    { id: 5, label: "SAT" },
    { id: 6, label: "ACT" },
    { id: 7, label: "GRE" },
    { id: 8, label: "GMAT" },
    { id: 9, label: "Without English Proficiency" },
    { id: 10, label: "Without GRE" },
    { id: 11, label: "Without GMAT" },
    { id: 12, label: "Without Maths" },
    {
      id: 13,
      label: "STEM Courses",
      disabled: true,
      tooltip:
        "To use this filter, Please select the USA as the only country in the country filter.",
    },
  ];



  export const studyAreasData = [
    { value: "1", label: "Agriculture, Forestry and Fishery" },
    { value: "2", label: "Architecture and Building" },
    { value: "3", label: "Arts" },
    { value: "4", label: "Commerce, Business and Administration" },
    { value: "5", label: "Computer Science and Information Technology" },
    { value: "6", label: "Education" },
    { value: "7", label: "Engineering and Engineering Trades" },
    { value: "8", label: "Environmental Science/Protection" },
    { value: "9", label: "Health" },
    { value: "10", label: "Humanities" },
    { value: "11", label: "Journalism and Information" },
    { value: "12", label: "Law" },
    { value: "13", label: "Life Sciences" },
    { value: "14", label: "Manufacturing and Processing" },
    { value: "15", label: "Mathematics and Statistics" },
    { value: "16", label: "Personal Services" },
    { value: "17", label: "Physical Sciences, Sciences" },
    { value: "18", label: "Security Services" },
    { value: "19", label: "Social and Behavioural Science" },
    { value: "20", label: "Social Services" },
    { value: "21", label: "Transport Services" },
    { value: "22", label: "Veterinary" },
  ];


  export const countriesData = [
    { value: "1", label: "United States of America" },
    { value: "2", label: "Australia" },
    { value: "3", label: "Canada" },
    { value: "4", label: "United Kingdom" },
    { value: "5", label: "New Zealand" },
    { value: "6", label: "Singapore" },
    { value: "7", label: "Dubai" },
    { value: "8", label: "Ireland" },
    { value: "9", label: "Germany" },
    { value: "10", label: "France" },
    { value: "11", label: "Sweden" },
    { value: "12", label: "Netherlands" },
    { value: "13", label: "Austria" },
    { value: "14", label: "Denmark" },
    { value: "15", label: "Finland" },
    { value: "16", label: "Italy" },
    { value: "17", label: "Hungary" },
    { value: "18", label: "Switzerland" },
    { value: "19", label: "Spain" },
    { value: "20", label: "Lithuania" },
    { value: "22", label: "Cyprus" },
    { value: "23", label: "Poland" },
    { value: "25", label: "Malaysia" },
    { value: "26", label: "Mauritius" },
    { value: "32", label: "China" },
    { value: "35", label: "Vietnam" },
    { value: "37", label: "Malta" },
    { value: "38", label: "Japan" },
    { value: "39", label: "Belgium" },
    { value: "40", label: "Russia" },
    { value: "41", label: "South Korea" },
    { value: "45", label: "India" },
    { value: "46", label: "Georgia" },
  ];