export const intakeOptions = [
    { value: 'January', label: 'January' },
    { value: 'February', label: 'February' },
    { value: 'March', label: 'March' },
    { value: 'April', label: 'April' },
    { value: 'May', label: 'May' },
    { value: 'June', label: 'June' },
    { value: 'July', label: 'July' },
    { value: 'August', label: 'August' },
    { value: 'September', label: 'September' },
    { value: 'October', label: 'October' },
    { value: 'November', label: 'November' },
    { value: 'December', label: 'December' },
];

export const yearOptions = [
    { value: '2021', label: '2021' },
    { value: '2022', label: '2022' },
    { value: '2023', label: '2023' },
    { value: '2024', label: '2024' },
    { value: '2025', label: '2025' },
    { value: '2026', label: '2026' },
];

export const countryOptions = [
    { value: "1", label: "United States of America" },
    { value: "2", label: "Australia" },
    { value: "3", label: "Canada" },
    { value: "4", label: "United Kingdom" },
    { value: "5", label: "New Zealand" },
    { value: "6", label: "Singapore" },
    { value: "7", label: "Dubai" },
    { value: "8", label: "Ireland" },
    { value: "9", label: "Germany" },
    { value: "10", label: "France" },
    { value: "11", label: "Sweden" },
    { value: "12", label: "Netherlands" },
    { value: "13", label: "Austria" },
    { value: "14", label: "Denmark" },
    { value: "15", label: "Finland" },
    { value: "16", label: "Italy" },
    { value: "17", label: "Hungary" },
    { value: "18", label: "Switzerland" },
    { value: "19", label: "Spain" },
    { value: "20", label: "Lithuania" },
    { value: "22", label: "Cyprus" },
    { value: "23", label: "Poland" },
    { value: "25", label: "Malaysia" },
    { value: "26", label: "Mauritius" },
    { value: "32", label: "China" },
    { value: "35", label: "Vietnam" },
    { value: "37", label: "Malta" },
    { value: "38", label: "Japan" },
    { value: "39", label: "Belgium" },
    { value: "40", label: "Russia" },
    { value: "41", label: "South Korea" },
    { value: "45", label: "India" },
    { value: "46", label: "Georgia" },
];
export const yearsOption = [
    { value: "2024", label: "2024" },
    { value: "2025", label: "2025" },
    { value: "2026", label: "2026" },
    { value: "2027", label: "2027" },
  ];

  export const IntakeYearsoptions = [
    { value: "*", label: "All" },
    { value: "1", label: "January" },
    { value: "2", label: "February" },
    { value: "3", label: "March" },
    { value: "4", label: "April" },
    { value: "5", label: "May" },
    { value: "6", label: "June" },
    { value: "7", label: "July" },
    { value: "8", label: "August" },
    { value: "9", label: "September" },
    { value: "10", label: "October" },
    { value: "11", label: "November" },
    { value: "12", label: "December" },
    { value: "13", label: "Spring" },
    { value: "14", label: "Summer" },
    { value: "15", label: "Fall" },
    { value: "16", label: "Winter" },
  ];
 export const ProgramLevelData = [
    { id: 1, label: "High School (11th - 12th)" },
    { id: 2, label: "UG Diploma/ Certificate/ Associate Degree" },
    { id: 3, label: "PG Diploma/Certificate" },
    { id: 4, label: "PG" },
    { id: 5, label: "UG+PG (Accelerated) Degree" },
    { id: 6, label: "Foundation" },
    { id: 7, label: "Short Term Programs" },
    { id: 8, label: "Pathway Programs" },
    { id: 9, label: "Twinning Programmes (UG)" },
    { id: 10, label: "Twinning Programmes (PG)" },
    { id: 11, label: "English Language Program" },
    { id: 12, label: "Online Programmes / Distance Learning" },
  ];  

  export const RequirementsData = [
    { id: 1, label: "PTE" },
    { id: 2, label: "TOEFL iBT" },
    { id: 3, label: "IELTS" },
    { id: 4, label: "DET" },
    { id: 5, label: "SAT" },
    { id: 6, label: "ACT" },
    { id: 7, label: "GRE" },
    { id: 8, label: "GMAT" },
    { id: 9, label: "Without English Proficiency" },
    { id: 10, label: "Without GRE" },
    { id: 11, label: "Without GMAT" },
    { id: 12, label: "Without Maths" },
    {
      id: 13,
      label: "STEM Courses",
      disabled: true,
      tooltip:
        "To use this filter, Please select the USA as the only country in the country filter.",
    },
  ];



  export const studyAreasData = [
    { value: "1", label: "Agriculture, Forestry and Fishery" },
    { value: "2", label: "Architecture and Building" },
    { value: "3", label: "Arts" },
    { value: "4", label: "Commerce, Business and Administration" },
    { value: "5", label: "Computer Science and Information Technology" },
    { value: "6", label: "Education" },
    { value: "7", label: "Engineering and Engineering Trades" },
    { value: "8", label: "Environmental Science/Protection" },
    { value: "9", label: "Health" },
    { value: "10", label: "Humanities" },
    { value: "11", label: "Journalism and Information" },
    { value: "12", label: "Law" },
    { value: "13", label: "Life Sciences" },
    { value: "14", label: "Manufacturing and Processing" },
    { value: "15", label: "Mathematics and Statistics" },
    { value: "16", label: "Personal Services" },
    { value: "17", label: "Physical Sciences, Sciences" },
    { value: "18", label: "Security Services" },
    { value: "19", label: "Social and Behavioural Science" },
    { value: "20", label: "Social Services" },
    { value: "21", label: "Transport Services" },
    { value: "22", label: "Veterinary" },
  ];


  export const countriesData = [
    { value: "1", label: "United States of America" },
    { value: "2", label: "Australia" },
    { value: "3", label: "Canada" },
    { value: "4", label: "United Kingdom" },
    { value: "5", label: "New Zealand" },
    { value: "6", label: "Singapore" },
    { value: "7", label: "Dubai" },
    { value: "8", label: "Ireland" },
    { value: "9", label: "Germany" },
    { value: "10", label: "France" },
    { value: "11", label: "Sweden" },
    { value: "12", label: "Netherlands" },
    { value: "13", label: "Austria" },
    { value: "14", label: "Denmark" },
    { value: "15", label: "Finland" },
    { value: "16", label: "Italy" },
    { value: "17", label: "Hungary" },
    { value: "18", label: "Switzerland" },
    { value: "19", label: "Spain" },
    { value: "20", label: "Lithuania" },
    { value: "22", label: "Cyprus" },
    { value: "23", label: "Poland" },
    { value: "25", label: "Malaysia" },
    { value: "26", label: "Mauritius" },
    { value: "32", label: "China" },
    { value: "35", label: "Vietnam" },
    { value: "37", label: "Malta" },
    { value: "38", label: "Japan" },
    { value: "39", label: "Belgium" },
    { value: "40", label: "Russia" },
    { value: "41", label: "South Korea" },
    { value: "45", label: "India" },
    { value: "46", label: "Georgia" },
  ];




  export const countries = [
    { id: 1, value: "Afghanistan" },
    { id: 2, value: "Albania" },
    { id: 3, value: "Algeria" },
    { id: 4, value: "American Samoa" },
    { id: 5, value: "Andorra" },
    { id: 6, value: "Angola" },
    { id: 7, value: "Anguilla" },
    { id: 8, value: "Antarctica" },
    { id: 9, value: "Antigua and Barbuda" },
    { id: 10, value: "Argentina" },
    { id: 11, value: "Armenia" },
    { id: 12, value: "Aruba" },
    { id: 13, value: "Australia" },
    { id: 14, value: "Austria" },
    { id: 15, value: "Azerbaijan" },
    { id: 16, value: "Bahamas The" },
    { id: 17, value: "Bahrain" },
    { id: 18, value: "Bangladesh" },
    { id: 19, value: "Barbados" },
    { id: 20, value: "Belarus" },
    { id: 21, value: "Belgium" },
    { id: 22, value: "Belize" },
    { id: 23, value: "Benin" },
    { id: 24, value: "Bermuda" },
    { id: 25, value: "Bhutan" },
    { id: 26, value: "Bolivia" },
    { id: 27, value: "Bosnia and Herzegovina" },
    { id: 28, value: "Botswana" },
    { id: 29, value: "Bouvet Island" },
    { id: 30, value: "Brazil" },
    { id: 31, value: "British Indian Ocean Territory" },
    { id: 32, value: "Brunei Darussalam" },
    { id: 33, value: "Bulgaria" },
    { id: 34, value: "Burkina Faso" },
    { id: 35, value: "Burundi" },
    { id: 36, value: "Cambodia" },
    { id: 37, value: "Cameroon" },
    { id: 38, value: "Canada" },
    { id: 39, value: "Cape Verde" },
    { id: 40, value: "Cayman Islands" },
    { id: 41, value: "Central African Republic" },
    { id: 42, value: "Chad" },
    { id: 43, value: "Chile" },
    { id: 44, value: "China" },
    { id: 45, value: "Christmas Island" },
    { id: 46, value: "Cocos (Keeling) Islands" },
    { id: 47, value: "Colombia" },
    { id: 48, value: "Comoros" },
    { id: 49, value: "Congo" },
    { id: 50, value: "Congo, the Democratic Republic of the" },
    { id: 51, value: "Cook Islands" },
    { id: 52, value: "Costa Rica" },
    { id: 53, value: "Cote D'Ivoire" },
    { id: 54, value: "Croatia" },
    { id: 55, value: "Cuba" },
    { id: 56, value: "Cyprus" },
    { id: 57, value: "Czech Republic" },
    { id: 58, value: "Denmark" },
    { id: 59, value: "Djibouti" },
    { id: 60, value: "Dominica" },
    { id: 61, value: "Dominican Republic" },
    { id: 62, value: "Ecuador" },
    { id: 63, value: "Egypt" },
    { id: 64, value: "El Salvador" },
    { id: 65, value: "Equatorial Guinea" },
    { id: 66, value: "Eritrea" },
    { id: 67, value: "Estonia" },
    { id: 68, value: "Ethiopia" },
    { id: 69, value: "Falkland Islands (Malvinas)" },
    { id: 70, value: "Faroe Islands" },
    { id: 71, value: "Fiji" },
    { id: 72, value: "Finland" },
    { id: 73, value: "France" },
    { id: 74, value: "French Guiana" },
    { id: 75, value: "French Polynesia" },
    { id: 76, value: "French Southern Territories" },
    { id: 77, value: "Gabon" },
    { id: 78, value: "Gambia" },
    { id: 79, value: "Georgia" },
    { id: 80, value: "Germany" },
    { id: 81, value: "Ghana" },
    { id: 82, value: "Gibraltar" },
    { id: 83, value: "Greece" },
    { id: 84, value: "Greenland" },
    { id: 85, value: "Grenada" },
    { id: 86, value: "Guadeloupe" },
    { id: 87, value: "Guam" },
    { id: 88, value: "Guatemala" },
    { id: 89, value: "Guinea" },
    { id: 90, value: "Guinea-Bissau" },
    { id: 91, value: "Guyana" },
    { id: 92, value: "Haiti" },
    { id: 93, value: "Heard Island and Mcdonald Islands" },
    { id: 94, value: "Holy See (Vatican City State)" },
    { id: 95, value: "Honduras" },
    { id: 96, value: "Hong Kong" },
    { id: 97, value: "Hungary" },
    { id: 98, value: "Iceland" },
    { id: 99, value: "India" },
    { id: 100, value: "Indonesia" },
    { id: 101, value: "Iran, Islamic Republic of" },
    { id: 102, value: "Iraq" },
    { id: 103, value: "Ireland" },
    { id: 104, value: "Israel" },
    { id: 105, value: "Italy" },
    { id: 106, value: "Jamaica" },
    { id: 107, value: "Japan" },
    { id: 108, value: "Jordan" },
    { id: 109, value: "Kazakhstan" },
    { id: 110, value: "Kenya" },
    { id: 111, value: "Kiribati" },
    { id: 112, value: "Korea, Democratic People's Republic of" },
    { id: 113, value: "Korea, Republic of" },
    { id: 240, value: "Kosovo" },
    { id: 114, value: "Kuwait" },
    { id: 115, value: "Kyrgyzstan" },
    { id: 116, value: "Lao People's Democratic Republic" },
    { id: 117, value: "Latvia" },
    { id: 118, value: "Lebanon" },
    { id: 119, value: "Lesotho" },
    { id: 120, value: "Liberia" },
    { id: 121, value: "Libyan Arab Jamahiriya" },
    { id: 122, value: "Liechtenstein" },
    { id: 123, value: "Lithuania" },
    { id: 124, value: "Luxembourg" },
    { id: 125, value: "Macao" },
    { id: 126, value: "Macedonia, the Former Yugoslav Republic of" },
    { id: 127, value: "Madagascar" },
    { id: 128, value: "Malawi" },
    { id: 129, value: "Malaysia" },
    { id: 130, value: "Maldives" },
    { id: 131, value: "Mali" },
    { id: 132, value: "Malta" },
    { id: 133, value: "Marshall Islands" },
    { id: 134, value: "Martinique" },
    { id: 135, value: "Mauritania" },
    { id: 136, value: "Mauritius" },
    { id: 137, value: "Mayotte" },
    { id: 138, value: "Mexico" },
    { id: 139, value: "Micronesia, Federated States of" },
    { id: 140, value: "Moldova, Republic of" },
    { id: 141, value: "Monaco" },
    { id: 142, value: "Mongolia" },
    { id: 143, value: "Montserrat" },
    { id: 144, value: "Morocco" },
    { id: 145, value: "Mozambique" },
    { id: 146, value: "Myanmar" },
    { id: 147, value: "Namibia" },
    { id: 148, value: "Nauru" },
    { id: 149, value: "Nepal" },
    { id: 150, value: "Netherlands" },
    { id: 151, value: "Netherlands Antilles" },
    { id: 152, value: "New Caledonia" },
    { id: 153, value: "New Zealand" },
    { id: 154, value: "Nicaragua" },
    { id: 155, value: "Niger" },
    { id: 156, value: "Nigeria" },
    { id: 157, value: "Niue" },
    { id: 158, value: "Norfolk Island" },
    { id: 159, value: "Northern Mariana Islands" },
    { id: 160, value: "Norway" },
    { id: 161, value: "Oman" },
    { id: 162, value: "Pakistan" },
    { id: 163, value: "Palau" },
    { id: 164, value: "Palestinian Territory, Occupied" },
    { id: 165, value: "Panama" },
    { id: 166, value: "Papua New Guinea" },
    { id: 167, value: "Paraguay" },
    { id: 168, value: "Peru" },
    { id: 169, value: "Philippines" },
    { id: 170, value: "Pitcairn" },
    { id: 171, value: "Poland" },
    { id: 172, value: "Portugal" },
    { id: 173, value: "Puerto Rico" },
    { id: 174, value: "Qatar" },
    { id: 175, value: "Reunion" },
    { id: 176, value: "Romania" },
    { id: 177, value: "Russian Federation" },
    { id: 178, value: "Rwanda" },
    { id: 179, value: "Saint Helena" },
    { id: 180, value: "Saint Kitts and Nevis" },
    { id: 181, value: "Saint Lucia" },
    { id: 182, value: "Saint Pierre and Miquelon" },
    { id: 183, value: "Saint Vincent and the Grenadines" },
    { id: 184, value: "Samoa" },
    { id: 185, value: "San Marino" },
    { id: 186, value: "Sao Tome and Principe" },
    { id: 187, value: "Saudi Arabia" },
    { id: 188, value: "Senegal" },
    { id: 189, value: "Serbia and Montenegro" },
    { id: 190, value: "Seychelles" },
    { id: 191, value: "Sierra Leone" },
    { id: 192, value: "Singapore" },
    { id: 193, value: "Slovakia" },
    { id: 194, value: "Slovenia" },
    { id: 195, value: "Solomon Islands" },
    { id: 196, value: "Somalia" },
    { id: 197, value: "South Africa" },
    { id: 198, value: "South Georgia and the South Sandwich Islands" },
    { id: 199, value: "Spain" },
    { id: 200, value: "Sri Lanka" },
    { id: 201, value: "Sudan" },
    { id: 202, value: "Suriname" },
    { id: 203, value: "Svalbard and Jan Mayen" },
    { id: 204, value: "Swaziland" },
    { id: 205, value: "Sweden" },
    { id: 206, value: "Switzerland" },
    { id: 207, value: "Syrian Arab Republic" },
    { id: 208, value: "Taiwan, Province of China" },
    { id: 209, value: "Tajikistan" },
    { id: 210, value: "Tanzania, United Republic of" },
    { id: 211, value: "Thailand" },
    { id: 212, value: "Timor-Leste" },
    { id: 213, value: "Togo" },
    { id: 214, value: "Tokelau" },
    { id: 215, value: "Tonga" },
    { id: 216, value: "Trinidad and Tobago" },
    { id: 217, value: "Tunisia" },
    { id: 218, value: "Turkey" },
    { id: 219, value: "Turkmenistan" },
    { id: 220, value: "Turks and Caicos Islands" },
    { id: 221, value: "Tuvalu" },
    { id: 222, value: "Uganda" },
    { id: 223, value: "Ukraine" },
    { id: 224, value: "United Arab Emirates" },
    { id: 225, value: "United Kingdom" },
    { id: 226, value: "United States" },
    { id: 227, value: "United States Minor Outlying Islands" },
    { id: 228, value: "Uruguay" },
    { id: 229, value: "Uzbekistan" },
    { id: 230, value: "Vanuatu" },
    { id: 231, value: "Venezuela" },
    { id: 232, value: "Vietnam" },
    { id: 233, value: "Virgin Islands, British" },
    { id: 234, value: "Virgin Islands, U.s." },
    { id: 235, value: "Wallis and Futuna" },
    { id: 236, value: "Western Sahara" },
    { id: 237, value: "Yemen" },
    { id: 238, value: "Zambia" },
    { id: 239, value: "Zimbabwe" },
    { id: 240, value: "Aland Islands" },
  ];
  
  