import mongoose from "mongoose";

const studentResSchema = new mongoose.Schema(
  {
    name:{ type: String},
    email: { type: String, unique: true },
    phoneNo: { type: Number },
    dob: { type: Date },
    gender: { type: String },
    maritalStatus: { type: String },
    address1: { type: String },
    address2: { type: String },
    country: { type: String },
    state: { type: String },
    city: { type: String },
    pinCode: { type: String },
    secodeAddress1: { type: String },
    secodeAddress2: { type: String },
    secodeCountry: { type: String },
    secondeState: { type: String },
    secondeCity: { type: String },
    secodePinCode: { type: String },
    passportNo: { type: String },
    issueDate: { type: Date },
    expiryData: { type: Date },
    issueCountry: { type: String },
    cityOfBirth: { type: String },
    countryOfBirth: { type: String },
    nationality: { type: String },
    citizenship: { type: String },
    isApplicanTACitizenOfMoreThanOneCountry: { type: Boolean },
    IsTheApplicantLivingAndStudyingInAnyOtherCountry: { type: Boolean },
    otherNationality: { type: String },
    livingCountry: { type: String },
    isApplicantImmigration: { type: Boolean },
    immigratedCountry: { type: String },
    DoesApplicantseriousMedicalCondition: { type: Boolean },
    medicalCondition: { type: String },
    HasApplicantVisaRefusalForAnyCountry: { type: Boolean },
    refusalVisaCountryName: { type: String },
    refusalVisaType: { type: String },
    HasApplicantEverBeenConvictedOfACriminalOffence: { type: Boolean },
    criminalOffenceType: { type: String },
    EmergencyContactsName: { type: String },
    EmergencyContactsEmail: { type: String },
    EmergencyContactsPhone: { type: String },
    EmergencyContactsRelationWithApplicant: { type: String },
    nameofTheOrganisationAndAddress: { type: String },
    position: { type: String },
    jobProfile: { type: String },
    workingFrom: { type: String },
    workingUpto: { type: String },
    modeOfSalary: { type: String },
    iAmCurrentlyWorkingHere: { type: String },
    postGraduateStates:{ type: String },
    countryOfEducation:{ type: String },
    highLevelEducation:{ type: String },
      postgraduate: {
        levelOfStudy: { type: String },
        nameOfTheInstitution: { type: String },
        countryOfStudy: { type: String },
        stateOfStudy: { type: String },
        cityOfStudy: { type: String },
        degreeAwarded: { type: String },
        Backlogs: { type: String },
        gradingSystem: { type: String },
        Score: { type: String },
        primaryLanguageOfInstruction: { type: String },
        startDate: { type: Date },
        endDate: { type: Date },
      },
      undergraduate: {
        levelOfStudy: { type: String },
        nameOfTheInstitution: { type: String },
        countryOfStudy: { type: String },
        stateOfStudy: { type: String },
        cityOfStudy: { type: String },
        degreeAwarded: { type: String },
        Backlogs: { type: String },
        gradingSystem: { type: String },
        Score: { type: String },
        primaryLanguageOfInstruction: { type: String },
        startDate: { type: Date },
        endDate: { type: Date },
      },
      grade12th: {
        levelOfStudy: { type: String },
        nameOfTheInstitution: { type: String },
        countryOfStudy: { type: String },
        stateOfStudy: { type: String },
        cityOfStudy: { type: String },
        degreeAwarded: { type: String },
        Backlogs: { type: String },
        gradingSystem: { type: String },
        Score: { type: String },
        primaryLanguageOfInstruction: { type: String },
        startDate: { type: Date },
        endDate: { type: Date },
        nameOfBoard:{ type: String }
      },
      grade10th: {
        levelOfStudy: { type: String },
        nameOfTheInstitution: { type: String },
        countryOfStudy: { type: String },
        stateOfStudy: { type: String },
        cityOfStudy: { type: String },
        degreeAwarded: { type: String },
        Backlogs: { type: String },
        gradingSystem: { type: String },
        Score: { type: String },
        primaryLanguageOfInstruction: { type: String },
        startDate: { type: Date },
        endDate: { type: Date },
        nameOfBoard:{ type: String }
      },
     studentTests: { type: Array }
  },
  { timestamps: true }
);

const StudentRegistration = mongoose.model("registerStudent", studentResSchema);
export default StudentRegistration;
