export const SEARCH_PROGRAM_REQUEST = 'SEARCH_PROGRAM_REQUEST';
export const SEARCH_PROGRAM_SUCCESS = 'SEARCH_PROGRAM_SUCCESS';
export const SEARCH_PROGRAM_FAILED = 'SEARCH_PROGRAM_FAILED';


export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const NEW_STUDENT_REQUEST = 'NEW_STUDENT_REQUEST';
export const NEW_STUDENT_SUCCESS = 'NEW_STUDENT_SUCCESS';
export const NEW_STUDENT_FAILED = 'NEW_STUDENT_FAILED';
  

export const GET_ALL_STUDENT_REQUEST = 'GET_ALL_STUDENT_REQUEST';
export const GET_ALL_STUDENT_SUCCESS = 'NEW_STUDENT_SUCCESS';
export const GET_ALL_STUDENT_FAILED = 'NEW_STUDENT_FAILED';

export const GET_ALL_STATE_REQUEST = 'GET_ALL_STATE_REQUEST';
export const GET_ALL_STATE_SUCCESS = 'GET_ALL_STATE_SUCCESS';
export const GET_ALL_STATE_FAILED = 'GET_ALL_STATE_FAILED';

export const STUDENT_INFO_REQUEST = 'STUDENT_INFO_REQUEST';
export const STUDENT_INFO_SUCCESS = 'STUDENT_INFO_SUCCESS';
export const STUDENT_INFO_FAILED = 'STUDENT_INFO_FAILED';


export const GET_STUDENT_DATA_BY_ID_REQUEST = 'GET_STUDENT_DATA_BY_ID_REQUEST';
export const GET_STUDENT_DATA_BY_ID_SUCCESS = 'GET_STUDENT_DATA_BY_ID_SUCCESS';
export const GET_STUDENT_DATA_BY_ID_FAILED = 'GET_STUDENT_DATA_BY_ID_FAILED';


export const UPDATE_STUDENT_INFO_REQUEST = 'UPDATE_STUDENT_INFO_REQUEST';
export const UPDATE_STUDENT_INFO_SUCCESS = 'UPDATE_STUDENT_INFO_SUCCESS';
export const UPDATE_STUDENT_INFO_FAILED = 'UPDATE_STUDENT_INFO_FAILED';