export const SEARCH_PROGRAM_REQUEST = 'SEARCH_PROGRAM_REQUEST';
export const SEARCH_PROGRAM_SUCCESS = 'SEARCH_PROGRAM_SUCCESS';
export const SEARCH_PROGRAM_FAILED = 'SEARCH_PROGRAM_FAILED';


export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const NEW_STUDENT_REQUEST = 'NEW_STUDENT_REQUEST';
export const NEW_STUDENT_SUCCESS = 'NEW_STUDENT_SUCCESS';
export const NEW_STUDENT_FAILED = 'NEW_STUDENT_FAILED';
  